#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/scrolwin.h>
#include <wx/wx.h>


/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_button_source_selectOnButtonClick( wxCommandEvent& event );
		void m_button_destination_selectOnButtonClick( wxCommandEvent& event );
		void m_choice_measurementsOnChoice( wxCommandEvent& event );
		void m_choice_compressionOnChoice( wxCommandEvent& event );
		void m_button_rotation_leftOnButtonClick( wxCommandEvent& event );
		void m_button_rotation_rightOnButtonClick( wxCommandEvent& event );
		void m_button_next_thumbnailOnButtonClick( wxCommandEvent& event );
		void OnPaint(wxPaintEvent& event);
		void OnSize(wxSizeEvent& event);
		void OnScroll(wxScrollWinEvent& event);
		void OnScrollThumbRelease(wxScrollWinEvent& event);
		void OnScrollThumbTrack(wxScrollWinEvent& event);

	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members


		wxImage m_image;
		wxBitmap m_bitmap;
		wxImage m_resizedImage;
		void UpdateImageSize();
		void Repaint();

		static const int DEFAULT_WIDTH = 900;
		static const int DEFAULT_HEIGHT = 600;




};

#endif // __GUIMyFrame1__
